let myList = [
    ["Tari Jaipong", "West Java", "Jaipongan, also known as jaipong, is a musical performance genre of the Sundanese people in the Sundanese language of West Java, Indonesia. Jaipongan includes revived indigenous arts, like gamelan, but it also did not ignore Western music completely despite the ban on rock and roll. It used its sensuality and the sensuality found in a traditional village music and dance, ketuk tilu. However, many believe it is something purely Indonesian or Sundanese in origin and style. It is developed predominately from rural folk forms and traditions as a purely indigenous form. The rise of cassettes and films has led to the popularity of the musical form of jaipongan. It has spread from its home in West Java's Sunda, to greater Java and Indonesia. It can be seen as many regional varieties of gong-chime performance found through much of Indonesia. As also an urban dance form, it is based primarily on the village forms of ketuk tilu and on the Indonesian martial arts, pencak silat. The musical genre is largely influenced from ketuk tilu with traces of the masked theater dance, topeng banjet and the wayang golek puppet theater. Ketuk tilu is its biggest influence, as a traditional Sudanese musical entertainment form."],
    
    ["Tari Kecak", "Bali", "Kecak (pronounced 'Kechak', alternate spellings: Kechak and Ketjak), known in Indonesian as Tari Kecak, is a form of Balinese hindu dance and music drama that was developed in the 1930s in Bali, Indonesia. Since its creation it has been performed primarily by men, with the very first women's kecak group starting in 2006. The dance mainly plays about the Ramayana and is traditionally performed in temples and villages across Bali.\n\nAlso known as the Ramayana Monkey Chant, the piece, performed by a circle of at least 150 performers wearing checked cloth around their waists, percussively chanting 'chak' and moving their hands and arms, depicts a battle from the Ramayana. The monkey-like Vanara led by Hanuman helped Prince Rama fight the evil King Ravana. Kecak has roots in sanghyang, a trance-inducing exorcism dance."],
    
    ["Tari Remong", "East Java", "Remong dance or commonly called remo dance is a dance that describes a prince who fought on the battlefield. This dance is often displayed as an introduction to performances in Ludruk art performances or welcome dances to welcome guests. Generally, this dance is performed by male dancers with brave movements."],
    
    ["Tari Pendet", "Bali", "Pendet is a traditional dance from Bali, Indonesia, in which floral offerings are made to purify the temple or theater as a prelude to ceremonies or other dances. Pendet is typically performed by young girls, carrying bowls of flower petals, handfuls of which are cast into the air at various times in the dance. Pendet can be thought of as a dance of greeting, to welcome the audience and invite spirits to enjoy a performance. It is one of the oldest Balinese dance, although the current form was codified in the 1950s."],
    
    ["Tari Gambyong", "Central Java", "Javanese society is known for its softness and flexibility. This is illustrated in an art, namely gambyong dance. This dance is performed by several female dancers with graceful and beautiful movements. In the time of the Surakarta Palace, gambyong dance was often used as an entertainment and dance reception for the guest of honor. But along with the times, this dance too."],
    
    ["Tari Serimpi", "Yogyakarta", "The Srimpi (also written as Serimpi) is a ritualized dance of Java, Indonesia, associated with the royal palaces of Yogyakarta and Surakarta. The srimpi dance is one of the classical dance of Central Java. Along with the bedhaya, srimpi epitomized the elegance (alus) character of the royal Javanese court, and the dance became a symbol of the ruler's power as well as the refinement of Javanese culture."],
    
    ["Tari Piring", "West Sumatera", "Tari Piring is a traditional Minangkabau plate dance from West Sumatra, Indonesia. The dance might be performed by a group of women, men or couples, each of them holds plates in each hands, and vigorously rotate or half rotate them in various formations and fast movements.\n\nThe dance demonstrates the skill of the dancers that manage balance and to move the ceramics plate swiftly without dropping or breaking the plates. Sometimes candles are lit on the plate, and this variant is called tari lilin (candle dance). Dancers hold the bottom of plates in the palm of their hands and swing them wildly using the inertia to keep the plate from falling. Dancers tap their plates with a ring on one of their fingers to animate their movement with sonic accompaniment.\n\nThis dance is usually performed as a ceremonial welcoming dance to honor the guests and elders to a traditional ceremony. Next to randai, saman, pendet and jaipongan, the dance is also one of popular Indonesian traditional dances performed in festivals abroad to promote Indonesian culture and tourism."],
    
    ["Tari Saman", "Aceh", "Saman (or the dance of a thousand hands) is one of the most popular dances in Indonesia. Its origin is from the Gayo ethnic group from Gayo Lues, Aceh province, Sumatra, and is normally performed to celebrate important occasions. The dance is characterized by its fast-paced rhythm and common harmony between dancers. These two elements are key figures of Saman, and are among the reasons Saman are widely known and practiced in Indonesia, besides being relatively easy to learn."]
]
